#!/bin/bash
docker run --rm -t \
  -e EXPO_TOKEN \
  -v ~/projects/jaccess/jaccessfe:/workspace \
  -v eas-gradle-cache:/root/.gradle \
  eas-android-builder \
  bash -c "git config --global --add safe.directory /workspace && eas $*"